version: 0.0
os: linux
files:
  - source: /minecraft_bot
    destination: /home/ec2-user/minecraft_bot
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
